#! /bin/bash

tempfiles=8

if [ ! -f $TMPDIR/pl.$tempfiles ]; then
for i in $(seq $tempfiles); do
	touch $TMPDIR/pl.$i &
done
wait
fi

t=($(ls $TMPDIR/pl.*))

grep -E -m 1 -o "iPhone.*|iPad.*|iPod.*|Architecture:.*" $1 > "${t[0]}" &
grep -E -m 1 -o "Launcher version:.*" $1 > "${t[1]}" &
grep -E -m 1 -o "Launching Minecraft .*|Minecraft version: .*" $1 > "${t[2]}" &
grep -E -m 1 -o "Loading Minecraft .* with .* Loader .*" $1 > "${t[3]}" &
grep -E -m 1 -o "Forge Mod Loader version .* for Minecraft .* loading|Forge mod loading, version .*, for MC .* with MCP .*" $1 > "${t[4]}" &
grep -E -m 1 -o "Mod Loader has successfully loaded .* mods|Forge Mod Loader has identified .* mods to load" $1 > ${t[7]} &
wait

p=($(< ${t[0]})) v=$(< ${t[1]}) m=($(< ${t[2]})) l=($(< ${t[3]})) f=($(< ${t[4]})) c=($(< ${t[7]}))

if [ ! -z ${p[2]} ]; then
	echo -e "Platform: ${p[2]}, version ${p[3]}, arm64\nDevice: ${p[0]}\n$v"

	grep -E -m 1 -o "dynamic-codesigning: .*" $1 > ${t[5]} &
	grep -E -m 1 -o "JIT has been enabled" $1 > ${t[6]} &
	wait

	d=($(< ${t[5]}))
	j=$(< ${t[6]})

	if [[ "${d[1]}" == "NO" && -z "$j" ]]; then
		echo -e "JIT availability: NO"
	else
		echo -e "JIT availability: yes"
	fi
	echo -e "Minecraft version: ${m[2]}"
elif [ ! -z ${p[1]} ]; then
	echo -e "Platform: Android, ${p[1]}\n$v"
	echo -e "Minecraft version: ${m[2]}"
else
	echo "Platform: Android, mod installer mode"
fi

if [ ! -z $l ]; then
	echo -e "Mod loader: ${l[4]} Loader, version ${l[6]} for Minecraft ${l[2]}"
elif [ ! -z "$f" ]; then
	echo -e "Mod loader: Forge, version ${f[4]} for Minecraft ${f[7]}"
	echo -e "Mod count: ${c[5]}"
fi

# Benchmark has been done on my device, by running the reader 10 times consecutively. 3.0.0 has been tweaked to disable basic checks step.
# 3.0.0: real 2.120s, single thread (user + sys) 5.089s
# 4.0.0 (this): real 1.082s (96% faster), single thread 2.265s (2.25x faster)
# Better code means less CPU utilization, yet better performance.
