#! /bin/bash

var1=$(egrep -m 1 -n -o "Mod resolution failed" $1)
var2=$(($(echo $var1 | cut -d ':' -f1)+2))
var3=$(sed -n "${var2}p" $1 | egrep -o "Reason: .*" | cut -d ':' -f2)
var4=${#var3}
var5=$(echo ${var3:2:$((var4-3))} | sed 's/, /\n/g' | sed 's/ /#/g')
echo "$var5"
for line in $var5
do
	case $(echo $line | cut -d '#' -f1) in
		HARD_DEP) echo "Mod $(echo $line | cut -d '#' -f2) lacks its dependencies" ;;
		NEG_HARD_DEP) echo "Mod $(echo $line | cut -d '#' -f2) breaks another mod" ;;
	esac
done
